// Writes `dist/embedded.ts` from the Vite build in `dist/client`, for via to embed
// the admin UI: `bun scripts/embed.ts`, which `bun run build` runs after `vite build`.
// It imports each file `with { type: "file" }`, which `bun build --compile` puts in
// the binary, and lists the CSP hashes of the shell's inline scripts. Everything
// is read from the build, not assumed. A build script's main, like npm/build.ts.
import { createHash } from "node:crypto";
import { readdir } from "node:fs/promises";
import { join, relative } from "node:path";

const dist = join(import.meta.dirname, "..", "dist");

const client = join(dist, "client");

const SHELL = "_shell.html";

const TYPES = new Map([
  [".js", "text/javascript; charset=utf-8"],
  [".css", "text/css; charset=utf-8"],
  [".svg", "image/svg+xml"],
]);

const contentType = (file: string) => {
  const type = TYPES.get(file.slice(file.lastIndexOf(".")));

  if (type === undefined) {
    console.error(`embed: no content type for ${file}; add its extension to TYPES`);
    process.exit(1);
  }

  return type;
};

/** The text of every inline script in `html`, in order: the scripts the CSP must allow. */
const inlineScripts = async (html: string) => {
  const scripts: Array<string> = [];
  let current: string | undefined;

  await new HTMLRewriter()
    .on("script", {
      element: (script) => {
        if (script.hasAttribute("src")) return;
        current = "";
        script.onEndTag(() => {
          scripts.push(current ?? "");
          current = undefined;
        });
      },
      text: (chunk) => {
        if (current !== undefined) current += chunk.text;
      },
    })
    .transform(new Response(html))
    .text();

  return scripts;
};

const files = (await readdir(client, { recursive: true, withFileTypes: true }))
  .filter((entry) => entry.isFile() && entry.name !== SHELL)
  .map((entry) => relative(client, join(entry.parentPath, entry.name)))
  .toSorted();

const hashes = (await inlineScripts(await Bun.file(`${join(client, SHELL)}`).text())).map(
  (script) => `sha256-${createHash("sha256").update(script).digest("base64")}`,
);

const source = `// Generated by apps/web/scripts/embed.ts from the build in ./client; don't edit.
import shell from "./client/${SHELL}" with { type: "file" };
${files.map((file, i) => `import file${i} from "./client/${file}" with { type: "file" };`).join("\n")}

export const ui = {
  shell,
  assets: [
${files.map((file, i) => `    { path: "/ui/${file}", file: file${i}, contentType: "${contentType(file)}" },`).join("\n")}
  ],
  scriptHashes: ${JSON.stringify(hashes)},
};
`;

await Bun.write(join(dist, "embedded.ts"), source);

console.log(`embedded ${files.length + 1} files, ${hashes.length} inline scripts`);
